
-- DROP TABLE IF EXISTS message CASCADE;
-- DROP TABLE IF EXISTS avatar CASCADE;
-- DROP TABLE IF EXISTS image_coin_url CASCADE;
DROP TABLE IF EXISTS history_purchase CASCADE;
DROP TABLE IF EXISTS balance_coin CASCADE;
DROP TABLE IF EXISTS sale_coin CASCADE;
DROP TABLE IF EXISTS coin CASCADE;
-- DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
